### ISSUE TITLE
Test suite error under Debian

### ISSUE THREAD

**Issue by tillea** [spatstat/spatstat.model#1]
Hi,
when I try to upgrade spatstat.model to its latest version 3.2-6 I get a test suite error which can be seen in the [full Debian CI log](https://salsa.debian.org/r-pkg-team/r-cran-spatstat.model/-/jobs/4689092#L1356).  It starts with

    > FULLTEST <- (nchar(Sys.getenv("SPATSTAT_TEST", unset="")) > 0)
    > ALWAYS   <- TRUE
    > cat(paste("--------- Executing",
    +           if(FULLTEST) "** ALL **" else "**RESTRICTED** subset of",
    +           "test code -----------\n"))
    --------- Executing **RESTRICTED** subset of test code -----------
    > #
    > # tests/kppm.R
    > #
    > # $Revision: 1.38 $ $Date: 2023/02/28 04:00:42 $
    > #
    > # Test functionality of kppm that depends on RandomFields
    > # Test update.kppm for old style kppm objects
    >
    > if(!FULLTEST)
    +   spatstat.options(npixel=32, ndummy.min=16)
    >
    > local({
    +
    +  fit <- kppm(redwood ~1, "Thomas") # sic
    +  fitx <- kppm(redwood ~x, "Thomas", verbose=TRUE)
    +  if(FULLTEST) {
    +    fitx <- update(fit, ~ . + x)
    +    fitM <- update(fit, clusters="MatClust")
    +    fitC <- update(fit, cells)
    +    fitCx <- update(fit, cells ~ x)
    +    #'
    +    Wsub <- owin(c(0, 0.5), c(-0.5, 0))
    +    Zsub <- (bdist.pixels(Window(redwood)) > 0.1)
    +    fitWsub <- kppm(redwood ~1, "Thomas", subset=Wsub)
    +    fitZsub <- kppm(redwood ~1, "Thomas", subset=Zsub)
    +    fitWsub

Please have a look at [the full log](https://salsa.debian.org/r-pkg-team/r-cran-spatstat.model/-/jobs/4689092#L1356) to see the complete error message as well as the R packages used when running this test.

Kind regards, Andreas.

**Comment by baddstats** [comment]
The error message is not very informative, but it's clear that this is related to the fact that the package `RandomFields` is no longer available on CRAN, and that several other packages which `RandomFields` depended upon are also about to be removed from CRAN.

The next version of `spatstat.model' will not depend on `RandomFields` so this problem should cease. Unfortunately this means that some of the functionality provided by `RandomFields` will no longer be available.

**Comment by tillea** [comment]
Hi Adrian, thanks for the quick response.

Am Thu, Oct 19, 2023 at 12:05:07AM -0700 schrieb Adrian Baddeley:
> The error message is not very informative, but it's clear that this is related to the fact that the package `RandomFields` is no longer available on CRAN, and that several other packages which `RandomFields` depended upon are also about to be removed from CRAN.

I do not think that this is due to the removal of `RandomFields` on CRAN.  The Debian package persists at the time of testing, was installed and should work.

> The next version of `spatstat.model' will not depend on `RandomFields` so this problem should cease. Unfortunately this means that some of the functionality provided by `RandomFields` will no longer be available.

Hopefully this will solve the issue.  Do you have any time line for this next version?

Kind regards, Andreas.

**Comment by baddstats** [comment]
`spatstat,model 3.2-8` has been published on CRAN. Let me know if any problems persist.

**Comment by tillea** [comment]
Am Mon, Oct 23, 2023 at 11:51:21PM -0700 schrieb Adrian Baddeley:
> `spatstat,model 3.2-8` has been published on CRAN. Let me know if any problems persist.

Thanks for the notification.  All tests are passing now.  Debian package uploaded, Andreas.
