### ISSUE TITLE
Error with envelope.ppm (probably envelopeEngine) for non regular windows

### ISSUE THREAD

**Issue by marcelinodelacruz** [spatstat/spatstat.model#2]
When computing envelopes for  an inhomogenous ppm  in a rotated window, the current version of envelope.ppm()  (spatstat.model v 3.2-8) returns an error. Last year's version (v 3.0-2) performed ok.

For example, this works in both versions:
```{} 
ex.ppp <- redwood
rwtrend <- density(ex.ppp)
ex.ppm<- ppm(ex.ppp~rwtrend)
ex.env<-envelope(ex.ppm, Kinhom, lambda=ex.ppm, nsim=19)
plot(ex.env, sqrt(./pi)-r~r, legend=FALSE)
``` 
 This example, with rotated window, works in the old version but not in the current one (it returns the error:
"Error in eval(call, as.list(envir), enclos = callframe) : 
  object 'X' not found"

```{}
ex.ppp <- redwood
newW <- rotate(ex.ppp$window, angle=pi/3, centre="centroid")
ex.ppp <- ex.ppp[newW]
rwtrend <- density(ex.ppp)
ex.ppm<- ppm(ex.ppp~rwtrend)
ex.env<-envelope(ex.ppm, Kinhom, lambda=ex.ppm, nsim=19)
plot(ex.env, sqrt(./pi)-r~r, legend=FALSE)
```

**Comment by baddstats** [comment]
Thanks for letting us know. I will investigate.

**Comment by baddstats** [comment]
The error occurred while executing `spatstat.explore::resolve.reciplambda` and is due to a scoping problem. I have (hopefully) fixed the bug in the development version `spatstat.explore 3.2-5.008`.

**Comment by marcelinodelacruz** [comment]
Thank you Adrian. It works again!
